-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.angajati
(
    id_angajat serial NOT NULL,
    nume character varying(40) COLLATE pg_catalog."default" NOT NULL,
    prenume character varying(40) COLLATE pg_catalog."default" NOT NULL,
    telefon character(10) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    id_localitate integer NOT NULL,
    data_nasterii date NOT NULL,
    id_universitate integer NOT NULL,
    data_angajarii date NOT NULL,
    functie character varying(50) COLLATE pg_catalog."default" NOT NULL,
    id_camin integer NOT NULL,
    CONSTRAINT angajati_pkey PRIMARY KEY (id_angajat)
);

CREATE TABLE IF NOT EXISTS public.camere
(
    id_camera serial NOT NULL,
    numar_camera character varying(10) COLLATE pg_catalog."default" NOT NULL,
    id_camin integer NOT NULL,
    etaj character varying(10) COLLATE pg_catalog."default" NOT NULL,
    tip_camera numeric(1, 0) NOT NULL,
    pret_curent_loc_camera numeric(5, 2) NOT NULL,
    CONSTRAINT camere_pkey PRIMARY KEY (id_camera)
);

CREATE TABLE IF NOT EXISTS public.camine_studenti
(
    id_camin serial NOT NULL,
    abreviere_camin character varying(10) COLLATE pg_catalog."default" NOT NULL,
    denumire_camin character varying(50) COLLATE pg_catalog."default" NOT NULL,
    id_universitate integer NOT NULL,
    cod_postal character(6) COLLATE pg_catalog."default" NOT NULL,
    adresa character varying(150) COLLATE pg_catalog."default" NOT NULL,
    telefon character(10) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    id_localitate integer NOT NULL,
    campus character varying(50) COLLATE pg_catalog."default" NOT NULL,
    categorie_camin character varying(10) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT camine_studenti_pkey PRIMARY KEY (id_camin)
);

CREATE TABLE IF NOT EXISTS public.cazari
(
    id_cazare serial NOT NULL,
    data_ora_cazare timestamp without time zone NOT NULL,
    id_repartizare integer NOT NULL,
    id_camera integer NOT NULL,
    data_ora_decazare timestamp without time zone NOT NULL,
    motiv_decazare character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT cazari_pkey PRIMARY KEY (id_cazare)
);

CREATE TABLE IF NOT EXISTS public.cereri
(
    id_cerere serial NOT NULL,
    data_ora_cerere timestamp without time zone NOT NULL,
    matricol integer NOT NULL,
    an_universitar numeric(4, 0) NOT NULL,
    id_camin1 integer NOT NULL,
    id_camin2 integer NOT NULL,
    id_camin3 integer NOT NULL,
    CONSTRAINT cereri_pkey PRIMARY KEY (id_cerere)
);

CREATE TABLE IF NOT EXISTS public.contracte_angajati
(
    id_angajat integer NOT NULL,
    data_modificare_contract date NOT NULL,
    salariu_brut numeric(8, 2) NOT NULL,
    vechime smallint NOT NULL,
    nr_pers_intretinere smallint NOT NULL,
    CONSTRAINT contracte_angajati_pkey PRIMARY KEY (id_angajat, data_modificare_contract)
);

CREATE TABLE IF NOT EXISTS public.email_angajati
(
    email character varying(50) COLLATE pg_catalog."default" NOT NULL,
    id_angajat integer NOT NULL,
    CONSTRAINT email_angajati_pkey PRIMARY KEY (email)
);

CREATE TABLE IF NOT EXISTS public.facultati
(
    id_facultate numeric(7, 0) NOT NULL,
    denumire_facultate character varying(150) COLLATE pg_catalog."default" NOT NULL,
    an_infiintare numeric(4, 0) NOT NULL,
    adresa character varying(150) COLLATE pg_catalog."default" NOT NULL,
    id_localitate integer NOT NULL,
    id_universitate integer NOT NULL,
    CONSTRAINT facultati_pkey PRIMARY KEY (id_facultate)
);

CREATE TABLE IF NOT EXISTS public.incasari
(
    id_incasare serial NOT NULL,
    data_ora_incasare timestamp without time zone NOT NULL,
    matricol_student_platitor integer NOT NULL,
    modalitate_plata character varying(10) COLLATE pg_catalog."default" NOT NULL,
    suma_incasata numeric(12, 2) NOT NULL,
    CONSTRAINT incasari_pkey PRIMARY KEY (id_incasare)
);

CREATE TABLE IF NOT EXISTS public.localitati
(
    id_localitate numeric(10, 0) NOT NULL,
    nume_localitate character varying(70) COLLATE pg_catalog."default" NOT NULL,
    regiune character varying(70) COLLATE pg_catalog."default" NOT NULL,
    id_tara integer NOT NULL,
    CONSTRAINT localitati_pkey PRIMARY KEY (id_localitate)
);

CREATE TABLE IF NOT EXISTS public.locuri_camine_facultati
(
    an_universitar integer NOT NULL,
    id_facultate integer NOT NULL,
    nr_locuri_repartizate numeric(3, 0) NOT NULL,
    CONSTRAINT locuri_camine_facultati_pkey PRIMARY KEY (an_universitar, id_facultate)
);

CREATE TABLE IF NOT EXISTS public.parcurs_studenti
(
    matricol integer NOT NULL,
    an_universitar numeric(4, 0) NOT NULL,
    id_facultate integer NOT NULL,
    ciclu_studii integer NOT NULL,
    specializare character varying(100) COLLATE pg_catalog."default" NOT NULL,
    an_studii numeric(1, 0) NOT NULL,
    nr_credite_acumulate numeric(3, 0) NOT NULL,
    medie_anuala numeric(4, 2) NOT NULL,
    CONSTRAINT parcurs_studenti_pkey PRIMARY KEY (matricol, an_universitar, id_facultate, ciclu_studii, specializare)
);

CREATE TABLE IF NOT EXISTS public.repartizari
(
    id_repartizare serial NOT NULL,
    data_ora_repartizare timestamp without time zone NOT NULL,
    id_cerere integer NOT NULL,
    id_camin_repartizat integer NOT NULL,
    CONSTRAINT repartizari_pkey PRIMARY KEY (id_repartizare)
);

CREATE TABLE IF NOT EXISTS public.studenti
(
    matricol serial NOT NULL,
    cnp character(13) COLLATE pg_catalog."default" NOT NULL,
    data_nasterii date NOT NULL,
    nume character varying(40) COLLATE pg_catalog."default" NOT NULL,
    prenume character varying(40) COLLATE pg_catalog."default" NOT NULL,
    adresa character varying(150) COLLATE pg_catalog."default" NOT NULL,
    telefon character(10) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    id_localitate integer NOT NULL,
    CONSTRAINT studenti_pkey PRIMARY KEY (matricol)
);

CREATE TABLE IF NOT EXISTS public.tari
(
    id_tara numeric(5, 0) NOT NULL,
    nume_tara character varying(30) COLLATE pg_catalog."default" NOT NULL,
    continent character varying(30) COLLATE pg_catalog."default" NOT NULL,
    populatie numeric(10, 0) NOT NULL,
    CONSTRAINT tari_pkey PRIMARY KEY (id_tara)
);

CREATE TABLE IF NOT EXISTS public.tel_angajati
(
    telefon character(10) COLLATE pg_catalog."default" NOT NULL,
    id_angajat integer NOT NULL,
    CONSTRAINT tel_angajati_pkey PRIMARY KEY (telefon)
);

CREATE TABLE IF NOT EXISTS public.ture_gardieni
(
    id_gardian integer NOT NULL,
    data_ora_inceput_tura timestamp without time zone NOT NULL,
    id_camin integer NOT NULL,
    data_ora_sfarsit_tura timestamp without time zone NOT NULL,
    CONSTRAINT ture_gardieni_pkey PRIMARY KEY (id_gardian, data_ora_inceput_tura)
);

CREATE TABLE IF NOT EXISTS public.ture_receptionisti
(
    id_receptionist integer NOT NULL,
    data_ora_inceput_tura timestamp without time zone NOT NULL,
    id_camin integer NOT NULL,
    data_ora_sfarsit_tura timestamp without time zone NOT NULL,
    CONSTRAINT ture_receptionisti_pkey PRIMARY KEY (id_receptionist, data_ora_inceput_tura)
);

CREATE TABLE IF NOT EXISTS public.universitati
(
    id_universitate numeric(6, 0) NOT NULL,
    nume_universitate character varying(190) COLLATE pg_catalog."default" NOT NULL,
    an_infiintare numeric(4, 0) NOT NULL,
    cod_postal character(6) COLLATE pg_catalog."default" NOT NULL,
    adresa character varying(150) COLLATE pg_catalog."default" NOT NULL,
    telefon character(10) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    id_localitate integer NOT NULL,
    CONSTRAINT universitati_pkey PRIMARY KEY (id_universitate)
);

CREATE TABLE IF NOT EXISTS public.vizite
(
    id_vizita serial NOT NULL,
    data_ora_inceput_vizita timestamp without time zone NOT NULL,
    data_ora_sfarsit_vizita timestamp without time zone NOT NULL,
    nume_prenume_vizitator character varying(100) COLLATE pg_catalog."default" NOT NULL,
    tel_vizitator character(10) COLLATE pg_catalog."default" NOT NULL,
    id_camera_vizitata integer NOT NULL,
    matricol_student_vizitat integer NOT NULL,
    observatii_vizita character varying(200) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT vizite_pkey PRIMARY KEY (id_vizita)
);

ALTER TABLE IF EXISTS public.angajati
    ADD CONSTRAINT angajati_id_camin_fkey FOREIGN KEY (id_camin)
    REFERENCES public.camine_studenti (id_camin) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.angajati
    ADD CONSTRAINT angajati_id_localitate_fkey FOREIGN KEY (id_localitate)
    REFERENCES public.localitati (id_localitate) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.angajati
    ADD CONSTRAINT angajati_id_universitate_fkey FOREIGN KEY (id_universitate)
    REFERENCES public.universitati (id_universitate) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.camere
    ADD CONSTRAINT camere_id_camin_fkey FOREIGN KEY (id_camin)
    REFERENCES public.camine_studenti (id_camin) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.camine_studenti
    ADD CONSTRAINT camine_studenti_id_localitate_fkey FOREIGN KEY (id_localitate)
    REFERENCES public.localitati (id_localitate) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.camine_studenti
    ADD CONSTRAINT camine_studenti_id_universitate_fkey FOREIGN KEY (id_universitate)
    REFERENCES public.universitati (id_universitate) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.cazari
    ADD CONSTRAINT cazari_id_camera_fkey FOREIGN KEY (id_camera)
    REFERENCES public.camere (id_camera) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.cazari
    ADD CONSTRAINT cazari_id_repartizare_fkey FOREIGN KEY (id_repartizare)
    REFERENCES public.repartizari (id_repartizare) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.cereri
    ADD CONSTRAINT cereri_id_camin1_fkey FOREIGN KEY (id_camin1)
    REFERENCES public.camine_studenti (id_camin) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.cereri
    ADD CONSTRAINT cereri_id_camin2_fkey FOREIGN KEY (id_camin2)
    REFERENCES public.camine_studenti (id_camin) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.cereri
    ADD CONSTRAINT cereri_id_camin3_fkey FOREIGN KEY (id_camin3)
    REFERENCES public.camine_studenti (id_camin) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.cereri
    ADD CONSTRAINT cereri_matricol_fkey FOREIGN KEY (matricol)
    REFERENCES public.studenti (matricol) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.contracte_angajati
    ADD CONSTRAINT contracte_angajati_id_angajat_fkey FOREIGN KEY (id_angajat)
    REFERENCES public.angajati (id_angajat) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.email_angajati
    ADD CONSTRAINT email_angajati_id_angajat_fkey FOREIGN KEY (id_angajat)
    REFERENCES public.angajati (id_angajat) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.facultati
    ADD CONSTRAINT facultati_id_localitate_fkey FOREIGN KEY (id_localitate)
    REFERENCES public.localitati (id_localitate) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.facultati
    ADD CONSTRAINT facultati_id_universitate_fkey FOREIGN KEY (id_universitate)
    REFERENCES public.universitati (id_universitate) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.incasari
    ADD CONSTRAINT incasari_matricol_student_platitor_fkey FOREIGN KEY (matricol_student_platitor)
    REFERENCES public.studenti (matricol) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.localitati
    ADD CONSTRAINT localitati_id_tara_fkey FOREIGN KEY (id_tara)
    REFERENCES public.tari (id_tara) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.locuri_camine_facultati
    ADD CONSTRAINT locuri_camine_facultati_id_facultate_fkey FOREIGN KEY (id_facultate)
    REFERENCES public.facultati (id_facultate) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.parcurs_studenti
    ADD CONSTRAINT parcurs_studenti_id_facultate_fkey FOREIGN KEY (id_facultate)
    REFERENCES public.facultati (id_facultate) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.parcurs_studenti
    ADD CONSTRAINT parcurs_studenti_matricol_fkey FOREIGN KEY (matricol)
    REFERENCES public.studenti (matricol) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.repartizari
    ADD CONSTRAINT repartizari_id_camin_repartizat_fkey FOREIGN KEY (id_camin_repartizat)
    REFERENCES public.camine_studenti (id_camin) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.repartizari
    ADD CONSTRAINT repartizari_id_cerere_fkey FOREIGN KEY (id_cerere)
    REFERENCES public.cereri (id_cerere) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.studenti
    ADD CONSTRAINT studenti_id_localitate_fkey FOREIGN KEY (id_localitate)
    REFERENCES public.localitati (id_localitate) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tel_angajati
    ADD CONSTRAINT tel_angajati_id_angajat_fkey FOREIGN KEY (id_angajat)
    REFERENCES public.angajati (id_angajat) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.ture_gardieni
    ADD CONSTRAINT ture_gardieni_id_camin_fkey FOREIGN KEY (id_camin)
    REFERENCES public.camine_studenti (id_camin) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.ture_gardieni
    ADD CONSTRAINT ture_gardieni_id_gardian_fkey FOREIGN KEY (id_gardian)
    REFERENCES public.angajati (id_angajat) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.ture_receptionisti
    ADD CONSTRAINT ture_receptionisti_id_camin_fkey FOREIGN KEY (id_camin)
    REFERENCES public.camine_studenti (id_camin) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.ture_receptionisti
    ADD CONSTRAINT ture_receptionisti_id_receptionist_fkey FOREIGN KEY (id_receptionist)
    REFERENCES public.angajati (id_angajat) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.universitati
    ADD CONSTRAINT universitati_id_localitate_fkey FOREIGN KEY (id_localitate)
    REFERENCES public.localitati (id_localitate) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.vizite
    ADD CONSTRAINT vizite_id_camera_vizitata_fkey FOREIGN KEY (id_camera_vizitata)
    REFERENCES public.camere (id_camera) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.vizite
    ADD CONSTRAINT vizite_matricol_student_vizitat_fkey FOREIGN KEY (matricol_student_vizitat)
    REFERENCES public.studenti (matricol) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;
